"""empty message

Revision ID: 28cc226e83d4
Revises: 9878e18873b6
Create Date: 2021-05-04 12:02:20.209769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cc226e83d4'
down_revision = '9878e18873b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_like_id_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_user_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'like', ['like_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_user_id_fkey', 'likes', 'user', ['user_id'], ['id'])
    op.create_foreign_key('likes_like_id_fkey', 'likes', 'like', ['like_id'], ['id'])
    # ### end Alembic commands ###
