"""empty message

Revision ID: 82eb6d7f1c3b
Revises: 28cc226e83d4
Create Date: 2021-05-04 18:49:43.320975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82eb6d7f1c3b'
down_revision = '28cc226e83d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_post_id_fkey', 'like', type_='foreignkey')
    op.drop_constraint('like_user_liked_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'like', 'user', ['user_liked'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_user_liked_fkey', 'like', 'user', ['user_liked'], ['id'])
    op.create_foreign_key('like_post_id_fkey', 'like', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
