"""empty message

Revision ID: c0c2953ca96e
Revises: 69b17822ed71
Create Date: 2021-03-04 17:52:49.199641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c2953ca96e'
down_revision = '69b17822ed71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_image', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_image')
    # ### end Alembic commands ###
